packages:
  - packages/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@xsai/shared': &xsai ^0.2.0-beta.2
  '@xsai-ext/providers-cloud': *xsai
  '@xsai-ext/providers-local': *xsai
  '@xsai-ext/shared-providers': *xsai
  '@xsai/embed': *xsai
  '@xsai/generate-speech': *xsai
  '@xsai/generate-text': *xsai
  '@xsai/generate-transcription': *xsai
  '@xsai/model': *xsai
  '@xsai/shared-chat': *xsai
  '@xsai/stream-text': *xsai
  '@xsai/tool': *xsai
  '@xsai/utils-chat': *xsai
  xsschema: *xsai
