/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioWaveform: typeof import('./components/AudioWaveform.vue')['default']
    BasicTextarea: typeof import('./components/BasicTextarea.vue')['default']
    Live2DViewer: typeof import('./components/Live2DViewer.vue')['default']
    MainStage: typeof import('./components/MainStage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
